spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/app/product/**,/hello
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: coupon
          uri: lb://mall-coupon
          predicates:
            - Path=/app/coupon/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
          - Path=/app/coupon/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: third-route
          uri: lb://mall-third
          predicates:
            - Path=/app/third/**
          filters:
            - RewritePath=/app/third/(?<segment>/?.*), /$\{segment}
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/app/member/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/app/ware/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /$\{segment}
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>/?.*), /renren-fast/$\{segment}
        - id: chheimall_host_route1
          uri: lb://mall-product
          predicates:
            - Host=mall.chhei.com
        - id: chheimall_seckill_route2
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.chhei.com
        - id: chheimall_host_route2
          uri: lb://mall-product
          predicates:
            - Host=item.chhei.com
        - id: chheimall_host_route3
          uri: lb://mall-search
          predicates:
            - Host=search.chhei.com
        - id: chheimall_host_route4
          uri: lb://mall-auth
          predicates:
            - Host=auth.chhei.com
        - id: chheimall_host_route5
          uri: lb://mall-cart
          predicates:
            - Host=cart.chhei.com
        - id: chheimall_host_route6
          uri: lb://mall-order
          predicates:
            - Host=order.chhei.com
server:
  port: 8070
