spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.100:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.56.100:8858
        client-ip: 192.168.56.1
  application:
    name: mall-auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.100
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: session:redis
server:
  port: 30000
  servlet:
    session:
      timeout: 30m